source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'UITags_Example' do
  pod "UITags", :path => "../"
end

target 'UITags_Tests' do
  pod "UITags", :path => "../"
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end
